// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ4grWwew3kV4r5ebj7KNLzRp9e4zZvQA',
    appId: '1:548406890449:web:fc5a9b247cebea0db55af0',
    messagingSenderId: '548406890449',
    projectId: 'id-card-scanner-38ac1',
    authDomain: 'id-card-scanner-38ac1.firebaseapp.com',
    storageBucket: 'id-card-scanner-38ac1.appspot.com',
    measurementId: 'G-C5CVYY808E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiRv03JvdZRkg0VhvIITzhafXY9FwSoWY',
    appId: '1:548406890449:android:decb09ab873f528eb55af0',
    messagingSenderId: '548406890449',
    projectId: 'id-card-scanner-38ac1',
    storageBucket: 'id-card-scanner-38ac1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFo-Osnlk_qFm5Fr3AA3Gk_-j0TredHOA',
    appId: '1:548406890449:ios:a14e1d353c419b75b55af0',
    messagingSenderId: '548406890449',
    projectId: 'id-card-scanner-38ac1',
    storageBucket: 'id-card-scanner-38ac1.appspot.com',
    iosBundleId: 'com.id.scanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFo-Osnlk_qFm5Fr3AA3Gk_-j0TredHOA',
    appId: '1:548406890449:ios:d2d1769836a960ddb55af0',
    messagingSenderId: '548406890449',
    projectId: 'id-card-scanner-38ac1',
    storageBucket: 'id-card-scanner-38ac1.appspot.com',
    iosBundleId: 'com.id.scanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ4grWwew3kV4r5ebj7KNLzRp9e4zZvQA',
    appId: '1:548406890449:web:d8c366da50b5fd5fb55af0',
    messagingSenderId: '548406890449',
    projectId: 'id-card-scanner-38ac1',
    authDomain: 'id-card-scanner-38ac1.firebaseapp.com',
    storageBucket: 'id-card-scanner-38ac1.appspot.com',
    measurementId: 'G-TVCMNTXTMZ',
  );
}
